# This is workflow name

name: Trigger file based

# runs on a trigger

on:
  push:
     branches: [main]
     paths: "**.html"

# these are jobs inside the workflow

jobs:
# this is the name of the job

  html:
  # this is github runner, each job runs on a runner
      runs-on: ubuntu-latest
      steps:
         - name: say hello to users
           run: echo "Hello Akash, How are you?"
         - name: say hello to username
           run: echo "Hello $USER"
